Repository Somil2104/CODEBLITZ, pull requests merged in 2025-02, with the labels that each got.

#18 Feat/readme
  README.md
  __pycache__/judge_api.cpython-313.pyc
  templates/attempt.html
Labels: acwoc, medium

#19 Added issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/pull_request.md
Labels: acwoc, easy

#20 Enhanced About Page Design and Interactivity
  app.py
  templates/about.html
  templates/layout.html
Labels: acwoc, hard

#22 Added LeaderBoard Section (Static)
  __pycache__/login_utils.cpython-312.pyc
  app.py
  instance/users.db
  requirements.txt
  templates/layout.html
  templates/leaderboard.html
Labels: acwoc, medium
